/**
 * Définition des catégories pour chaque profil et besoin
 */

export const PROFILE_CATEGORIES = {
  animateur: [
    "Jeux et activités sportives",
    "Activités manuelles et créatives",
    "Recettes de cuisine",
    "Grands jeux et animations",
    "Chants, musique et veillées",
    "Gestion de groupe",
    "Sujets sociétaux",
    "Réglementation et sécurité (ACM)",
    "Connaissance des publics",
    "Projets d'animation",
    "Vie quotidienne",
  ],
  formateur: [
    "Pédagogie et méthodologie",
    "Connaissance de l'enfant",
    "Formation BAFA/BAFD",
    "Outils de formation",
    "Cadre réglementaire",
    // Approfondissements
    "Accueil d'enfant en situation de handicap",
    "Accueil de loisirs et temps périscolaires",
    "Activités d'expression et théâtrales",
    "Activités de bord de mer et découverte de l'environnement",
    "Activités manuelles, activités de récupération",
    "Animation nature et médiation animale : connaissance du cheval",
    "Animation positive : Happy Boîte à outils !",
    "Animer 2.0",
    "Animer la petite enfance",
    "Animer les accueils et séjours 6-12 ans",
    "Animer les accueils et séjours des préados et ados",
    "Animer les droits de l'enfant",
    "Animer sa ville, animer dans sa ville",
    "Animer un accueil de loisirs associé à l'école (ALAE)",
    "Animer un séjour à l'étranger",
    "Arts de la rue",
    "Arts du cirque",
    "Arts et traditions",
    "Ateliers et projets audiovisuels",
    "Contes et légendes",
    "Création de jeux et animation de nouvelles activités",
    "Danses et créations chorégraphiques",
    "Du mini camp aux séjours (itinérant, à l'étranger…)",
    "Environnement et développement durable",
    "Gestion de conflits et jeux coopératifs",
    "Grand jeux",
    "Grands jeux et activités physiques autour de la balle ovale",
    "Grands jeux, veillées et journées exceptionnelles",
    "Jeux coopératifs",
    "Jeux de rôles, jeux du monde",
    "Musique et percussions",
    "Nature, patrimoine et découverte",
    "Pistes, énigmes et mystères",
    "Planètes et Sciences",
    "Préparation au rôle d'assistant sanitaire",
    "Préparation au rôle d'assistant sanitaire + PSC1",
    "PSC1",
    "Qualification au surveillant de baignade",
    "Qualification au surveillant de baignade + PSC1",
    "Qualification Canoë Kayak",
    "SKI",
    "Sports et jeux collectifs, activités physiques",
    "Veillées, spectacles et fêtes",
  ],
  directeur: [
    "Gestion de projet pédagogique",
    "Management d'équipe",
    "Aspects administratifs et financiers",
    "Sécurité et prévention",
    "Communication (parents, partenaires, équipe)",
    "Réglementation ACM et législation",
    "Ressources humaines (recrutement, formation)",
    "Qualité et évaluation",
  ],
  stagiaire: [
    "Découverte de l'animation",
    "Activités clés en main",
    "Connaissance de l'enfant",
    "Vie quotidienne",
    "Préparation aux épreuves",
    "Jeux et animations simples",
    "Gestion de groupe (bases)",
    "Sécurité et réglementation (essentiel)",
  ],
  decouvrir: [
    "Ressources publiques",
    "Exemples d'activités",
    "Jeux et animation",
    "Animer un anniversaire, une fête",
    "Et autres surprises",
  ],
} as const;

export const NEED_CATEGORIES = {
  preparer: [
    "Activités clés en main (0-30 min de préparation)",
    "Jeux sans matériel",
    "Fiches express",
    "Animations de dernière minute",
  ],
  projet: [
    "Projets thématiques complets",
    "Séjours et mini-camps",
    "Projets d'animation sur plusieurs séances",
    "Outils de planification",
  ],
  gerer: [
    "Gestion de conflits",
    "Situations d'urgence",
    "Comportements difficiles",
    "Communication avec les parents",
  ],
  competences: [
    "Formations et tutoriels",
    "Approfondissements thématiques",
    "Pédagogie et méthodologie",
    "Réglementation et cadre légal",
  ],
} as const;

export type ProfileType = keyof typeof PROFILE_CATEGORIES;
export type NeedType = keyof typeof NEED_CATEGORIES;
